### ISSUE TITLE
Inconsistent Parsing of Root Flag with Equal Sign in Default Behavior

### ISSUE THREAD

**Issue by pemson-pereira** [dasginganinja/drush-launcher#14]
**Description:**
When using the `--root` flag with the equal sign (`=`) in the default behaviour, the flag is not identified as expected. For instance, the syntax `--root=/path` does not behave correctly, while the alternative syntax `--root /path` works as intended.

**Steps to Reproduce:**
1. Execute a command with the `--root=/path` syntax.
2. Observe that the root flag is not recognised or applied correctly.

**Expected Behavior:**
The `--root=/path` syntax should be equivalent to `--root /path` and both should be parsed consistently.

**Actual Behavior:**
The `--root=/path` syntax is not recognised as expected, leading to inconsistencies in the default behaviour.

**Proposed Resolution**
Integrating the [Go Flag package](https://pkg.go.dev/flag )

**Comment by dasginganinja** [comment]
I'd consider this a big bug as part of the recent update. We had previously been using the Go Flag module but I couldn't find a great way to make it behave with arguments that weren't defined? 

Let me try and get this fixed and a new release pushed this week. I apologize for any inconvenience. 
For the time being, please use the previous v1.0.0 tag.

Thank you for the report!

**Comment by dasginganinja** [comment]
I started to take a look at this today. I plan to have a fix up this week.

**Comment by dasginganinja** [comment]
I've put this up on the main branch in case anybody wants to test locally.

`go build` on your platform *should be* enough to get it going since we have no external deps.

**Comment by dasginganinja** [comment]
I just released v1.0.2 that includes a fix for this.  Thank you for the reports!
